name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.1.16f1-windows-mono-0.15.0
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_v2021.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2021.x.ulf

        # Activate unity
        - name: Activate Unity
          run: /opt/unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2021.x.ulf || exit 0

        # Build Windows and OSX
        - name: Build Windows Player
          run: /opt/unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildWindows64Player ./bin-win64/CISample.exe
        # - name: Build OSX Player
        #  run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildOSXUniversalPlayer ./bin-osx/CISample.app

        - name: Archive Windows Build
          uses: actions/upload-artifact@v1
          with:
            name: CISampleWin64Binary
            path: ./bin-win64

        # - name: Archive Mac Build
        #   uses: actions/upload-artifact@v1
        #   with:
        #     name: CISampleOSXBinary
        #     path: ./bin-osx
